version: '3.8'

services:
  api:
    build: .
    container_name: api
    command: uvicorn ninety_seven_things.main:app --reload --reload-dir src --use-colors --host 0.0.0.0 --port ${API_PORT}
    env_file:
      - .env
    expose:
      - ${API_PORT}
    depends_on:
      - nst-mongo
      - nst-redis
    links:
      - nst-mongo
    volumes:
      - ./:/app
      - ./data:/data
    ports:
      - "${API_PORT}:${API_PORT}"

  nst-redis:
    container_name: nst-redis
    image: redis:7-alpine
    command: --port ${REDIS_PORT}
    expose:
      - ${REDIS_PORT}

  nst-mongo:
    container_name: nst-mongo
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    expose:
      - ${MONGO_PORT}
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
      - '--port'
      - "${MONGO_PORT}"
